### PR TITLE
Fixing namespace inconsistency issue

### PR DESCRIPTION
**Pull request by foram-splunk**
Fixing 
- https://github.com/splunk/splunk-connect-for-kubernetes/issues/133 
- https://github.com/splunk/splunk-connect-for-kubernetes/issues/256
- https://github.com/splunk/splunk-connect-for-kubernetes/issues/263

### CODE REVIEW

**Comment by rockb1017** [comment]
this will resolve inconsistency issue, but it will break existing queries.

**Comment by rockb1017** [comment]
so is it hard coding field name to `container-name` and `pod-name` ?
but now we are changing it to `container_name` and `pod_name`?

**Comment by foram-splunk** [comment]
As mentioned in the issues , there is inconsistency due to `-` and `_` for name , so have to change it to either one (`_`). As far as queries are concerned , we can add docs for next release. What are your thoughts on this , should we update docs or should I close PR ?

**Comment by rockb1017** [comment]
Okay, it is better to be consistent, but we should be careful for releasing breaking changes. let's hold off on this.

**Comment by princeba84** [comment]
This post is more than year old but I still have same issues. I am using Kubernetes 1.20 and Splunk 9.0.2.
Someone has update on this please ?

**Pull request closed without merging**
